project: 
  type: website
  output-dir: docs
  
bibliography: references.bib
csl: apa.csl
  
website: 
  title: Meta-Analysis of a Complete Micro-PK Database from the LMU Lab
  navbar: 
    background: light
    left: 
      - index.qmd
      - text: "Experiments"
        file: experiments.qmd
      - changeofevidence.qmd
      - metaanalysis.qmd
      #- metaanalysis-shiny.qmd
      
  sidebar: 
    - title: "Experiments"
      style: "docked"
      background: light
      alignment: "center"
      contents: 
        - experiments.qmd
        - auto: studies
    - title: "Change of Evidence"
      style: "docked"
      background: light
      alignment: "center"
      contents: 
        - text: "Overview"
          file: changeofevidence.qmd
        - text: "Measures"
          file: coe-measures.qmd
    - title: "Meta-Analyses"
      style: "docked"
      background: light
      alignment: "center"
      contents: 
        - text: "Micro-PK"
          file: metaanalysis.qmd
        - text: "Change of Evidence"
          file: coe-metaanalysis.qmd
        - text: "Discussion"
          file: discussion.qmd
#        - text: "Shiny App"
#          file: metaanalysis-shiny.qmd
        
  back-to-top-navigation: false
  comments:
    hypothesis:
      theme: classic
      showHighlights: whenSidebarOpen
  page-footer:
    center: "&copy; 2024 Dr. Moritz Dechamps"
    background: light