project: 
  type: website
  output-dir: docs
  
website: 
  title: Maier Lab Report on Micro-Pk
  navbar: 
    background: light
    left: 
      - index.qmd
      - experiments.qmd
      - changeofevidence.qmd
      - metaanalysis.qmd
  back-to-top-navigation: true
  page-footer:
    center: "&copy; 2024 Dr. Moritz Dechamps"
    background: light