project: 
  type: website
  output-dir: docs
  
bibliography: references.bib
csl: apa.csl
  
website: 
  title: The LMU Micro-PK Project
  navbar: 
    background: light
    left: 
      - index.qmd
      - text: "Experiments"
        file: experiments.qmd
      - changeofevidence.qmd
      - metaanalysis.qmd
      - metaanalysis-shiny.qmd
      
  sidebar: 
    - title: "Experiments"
      style: "docked"
      background: light
      alignment: "center"
      contents: 
        - experiments.qmd
        - auto: studies
        
  back-to-top-navigation: false
  page-footer:
    center: "&copy; 2024 Dr. Moritz Dechamps"
    background: light