---
title: "Overview"
format: 
  html:
    page-layout: full
    #css: "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css"
#toc: true
toc-depth: 3
editor: visual
execute: 
  echo: false
  warning: false
---

Last update: 04 May 2020

```{r}
st <- readRDS("overview.rds")

library(formattable)
library(dplyr)
library(knitr)
library(kableExtra)

links = c(
  "studies/lovekind.html",
  "studies/prayer.html",
  "studies/monks.html",
  "studies/monks.html",
  "studies/monks.html",
  "studies/monks.html",
  "studies/meditation.html",
  "studies/meditation.html",
  "studies/sound.html",
  "studies/allgood.html",
  "studies/bandit.html",
  "studies/cointoss.html",
  "studies/incongruence.html",
  "studies/incongruence.html",
  "studies/smokers1.html",
  "studies/smokers1.html",
  "studies/smokers2.html",
  "studies/smokers2.html",
  "studies/smokers3.html",
  "studies/psysc.html",
  "studies/psysc.html",
  "studies/psysc.html",
  "studies/psysc.html",
  "studies/psysc.html",
  "studies/psysc.html",
  "studies/relax.html",
  "studies/priming1.html",
  "studies/priming1.html",
  "studies/priming2.html",
  "studies/priming2.html",
  "studies/priming3.html",
  "studies/priming3.html",
  "studies/erotic1.html",
  "studies/erotic2.html"
)

ft <- st %>%
  mutate(
    across(where(is.numeric), ~ round(., 2)),
    `Hits (%)` = color_tile("coral2","cornflowerblue")(`Hits (%)`),
    p = cell_spec(p, bold = ifelse(p < 0.05, TRUE, FALSE)),
    Experimental = ifelse(Experimental, "âœ”", "âœ–"),
    Experimental = cell_spec(Experimental, color = ifelse(Experimental == "âœ”", "darkgreen", "red")),
    Labstudy = ifelse(Labstudy, "ðŸ ", "ðŸŒ"),
    Study = text_spec(Study, link = links)
    )

kbl(ft, escape = F,
    col.names = c("Study",
                  "Effect expected",
                  "N",
                  "Trials",
                  "M",
                  "SD",
                  "Hits (%)",
                  "t",
                  "p",
                  "ES",
                  "Var",
                  "BF",
                  "Direction",
                  "Lab/Online"),
    align = "lccccccccccccc") %>%
  kable_classic("hover", fixed_thead = T)
```

## General Information

### Generation of Randomness

When not specified otherwise, we used a quantum-based random number generator (qRNG) *Quantis* by idquantique to generate true randomness and coupled the outcome of these random events to the display of relevant stimulus material. A micro-Pk effect should result in a (temporary; see [*change of evidence*](changeofevidence.html)) biasing of the qRNG outcome corresponding to the presentation of more or less of the relevant stimuli.

### Online Studies

If an experiment is classified as an online study, it was set up with the software jsPsych [@deleeuw2023] and running on a dedicated web server in the departments IT infrastructure. A qRNG is directly connected to the web server via USB and provides random events without a buffer.
