---
title: "About"
format: 
  html:
    page-layout: full
editor: visual
sidebar: false
execute: 
  echo: false
---

## The LMU Micro-PK Project

This project investigates the relationship between mind and matter by studying observational effects on quantum state reductions. Located at LMU Munich, the project is conducted under the supervision of [Prof. Dr. Markus Maier](https://www.psy.lmu.de/gp/people/leitung/maier/index.html) and [Dr. Moritz Dechamps](https://www.psy.lmu.de/gp/people/mitarbeiter/moritz-dechamps/index.html).

## Micro-Psychokinesis

The studies within this project utilize a paradigm known as Micro-Psychokinesis (Micro-PK). Micro-PK refers to the mental influence on inanimate, probabilistic systems, such as quantum random number generators (qRNGs), with effects detectable through statistical means [@varvoglis2015micro].

## The Lab Report

This website provides a continuously updated overview of all Micro-PK experiments conducted at the lab, along with their results. This initiative aims to counteract biases associated with selective publication of results [see e.g., @publicat2005] by promoting transparency and reproducibility.

For each study, the [main results](experiments.html) (including distinctions between experimental and control conditions where applicable) and outcomes of the *'[change of evidence](changeofevidence.html)'* analyses are presented. Additionally, the report offers meta-analytical assessments of both [conventional effect](metaanalysis.html) measures and [change of evidence](coe-metaanalysis.html) measures alongside a [discussion](discussion.html) of the results.

### Included Studies

This report includes all studies conducted at the LMU Lab that explore a general and universal Micro-PK effect. Excluded are case studies of individuals or studies on related psi effects such as precognition. Detailed information on each study, along with relevant data and resources, can be found in the [experiments section](experiments.html).

### Versions

The report is regularly updated to include new studies and results. The current version  includes all studies conducted from the beginning of the project in 2016 until 04 May 2020.

### Comments and Feedback

Instead of a traditional peer-review process, we would like to encourage you to provide feedback on the report using the hypothesis.is platform, which can be activated by opening the sidebar on the right. This way, we hope to foster a more open and transparent dialogue about the results and methods presented here.

## Reference This Report

If you find this report useful and wish to cite it in your work, please use the following citation format:

Dechamps, M. C. (2024). *Meta-Analysis of a Complete Micro-PK Database from the LMU Lab: Years 2016-2020*. <https://doi.org/10.5281/zenodo.13643264>. Retrieved from <https://mrzdcmps.github.io/labreport>
